// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"
)

type Category struct {
	CategoryID  int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Post struct {
	PostID    int32
	Content   string
	UserID    sql.NullInt32
	TopicID   sql.NullInt32
	CreatedAt sql.NullTime
}

type Role struct {
	RoleID      int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Session struct {
	SessionID  int32
	UserID     sql.NullInt32
	SessionKey string
	CreatedAt  sql.NullTime
	ExpiresAt  time.Time
}

type Topic struct {
	TopicID    int32
	Title      string
	Content    sql.NullString
	UserID     sql.NullInt32
	CategoryID sql.NullInt32
	CreatedAt  sql.NullTime
}

type User struct {
	UserID       int32
	Username     string
	Email        string
	PasswordHash string
	DarkTheme    bool
	CreatedAt    sql.NullTime
}

type UserRole struct {
	UserID int32
	RoleID int32
}
